### ISSUE TITLE
Only set new GitHub SSH key and PAC if needed.

### ISSUE THREAD

**Issue by a-t-0** [Simple-Setup/Self-host-GitLab-Server-and-Runner-CI#108]
- [x] To speed up the installation and dev/testing process, only create a GitHub SSH key and PAC if needed. Determine whether a function already exists that performs such a check. (Hint: https://github.com/TruCol/Self-host-GitLab-CI-for-GitHub/issues/81)
- [x] First check if such a GitHub ssh key exists locally, and if yes:
- [x] Verify if it works, if it does work, skip adding a GitHub ssh key.
- [x] Then check if such a GitHub personal access token exists locally, and if yes:
- [x]  Verify if it works, if it does work, skip adding a GitHub personal access token.

Relevant code:
```
set_personal_github_pat_and_verify() 
# TODO: first verify if the GitHub pat exists and can be used, before
	# creating a new one.
```

**Comment by a-t-0** [comment]
Done, it works.
