### ISSUE TITLE
Change else to elif in the setup() function of tests.

### ISSUE THREAD

**Issue by a-t-0** [Simple-Setup/Self-host-GitLab-Server-and-Runner-CI#62]
Currently, the `setup()` functions of the tests in:`server_required - breaks_server` and `server_required - preserves_server`  contain:
```
if [ $(gitlab_server_is_running | tail -1) == "RUNNING" ]; then
...
else
###		#+ uninstall and re-installation by default
..
fi
```
- [ ] That `else` should be changed to `elif [ $(gitlab_server_is_running | tail -1) == "NOTRUNNING" ]; then` to only uninstall the server if it is not already running. 

- [ ] Additionally, throw an exception if the status is neither `RUNNING` nor `NOTRUNNING`, like done at: 
```
elif [ "$gitlab_server_is_running" == "RUNNING" ]; then
		echo "The GitLab server is already running."
	else
		echo "An error occured, the GitLab server status was neither RUNNING, nor NOTRUNNING."
		exit 123
	fi
```
in `src/install_and_boot_gitlab_server.sh`.
 - [ ] Propagate this change to all files in:
```
############### server_required - preserves_server##########################
# New test
# TODO: move into right folder
# TODO: (if needed) separate into: requires installation, does not require installation.
./test/libs/bats/bin/bats test/test_run_ci_on_github_repo.bats

### Partially working (requires installation)
# TODO: separate into: requires installation, does not require installation.
###./test/libs/bats/bin/bats test/server_required/preserves_server/test_helper_github_status.bats
###./test/libs/bats/bin/bats test/server_required/breaks_server/test_docker.bats

# Fail: Verify apache2 is not found.
###./test/libs/bats/bin/bats test/no_server_required/preserves_server/test_support_programs.bats


############### server_required - breaks_server##########################
```
 - [ ] Then remove the `setup()` checks to see if the server is running from the tests that do not require the GitLab server to be running. Ps. Take care to not delete custom setup procedures of those `setup()` functions that do something else than check if GitLab server is already running (even though the GitLab server does not have to be running for those tests).
